# Generated by Django 5.1.7 on 2025-03-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendorhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(upload_to="product_files"),
        ),
    ]
