# Generated by Django 5.1.7 on 2025-03-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendorhub", "0002_alter_category_options_alter_product_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
