# Generated by Django 5.1.7 on 2025-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendorhub", "0003_alter_orderdetail_stripe_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
