# Generated by Django 5.1.7 on 2025-03-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
