# Generated by Django 5.1.7 on 2025-03-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_is_vendor"),
        ("vendorhub", "0003_alter_orderdetail_stripe_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="vendorhub.vendor",
            ),
        ),
    ]
